name: 'Build devcontainer'
on:
  schedule:
    # 1st every months
    - cron: '0 0 1 * *' 
  workflow_dispatch:
    # Manual run

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build container and do nothing
        uses: devcontainers/ci@v0.2
        with:
          # Should match to devcontainer.json setup
          imageName: ghcr.io/nedsociety/HS-devcontainer
          runCmd: echo Done.
